remote_theme              : mmistakes/minimal-mistakes
minimal_mistakes_skin     : dark


title                     : Andrea Scorsoglio
email                     : andreascorsoglio@email.arizona.edu
description               : "On this website I present myself and my research at the Space Systems Engineering Laboratory
(University of Arizona). You will find space applications of reinforcement learning and computer vision."

github_username: andreascorsoglio

locale                    : "en-US"

subtitle                  : "Aerospace Systems Engineer" # site tagline that appears below site title in masthead

name                      : "Andrea Scorsoglio"

search                    : true
search_full_content       : true # true, false (default)

# logo: "fas fa-space-shuttle"

# Build settings
markdown                  : kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
# paginate_path: /blog/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Andrea Scorsoglio"
  avatar : "/assets/images/AndreaScorsoglio_squared.jpg"
  bio    : "PhD student at University of Arizona. I focus on space applications of
  reinforcement learning, simulation and computer vision"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andreascorsoglio"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Andrea-Scorsoglio"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrea-scorsoglio-409a72140/"
    - label: "SSEL"
      icon: "fas fa-fw fa-link"
      url: "https://www.ssel.arizona.edu/"
    - label: "Resume/CV"
      icon: "fas fa-fw fa-download"
      url: "https://andreascorsoglio.github.io/about/"

    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andreascorsoglio"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Andrea-Scorsoglio"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrea-scorsoglio-409a72140/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# analytics:
#   provider: "custom"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
